# Site settings
title: chzhbob's blog
email: chzhbob@gmail.com
description: "We Sing We Dance We Steal Things"

baseurl: "http://acgun.net"


# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments